// Auto-generated by scripts/export-credentials.ts
// Do not edit manually — run `bun run export` to regenerate
export const enrolledUsers: Array<{ id: string; username: string }> = [
	{
		"id": "cd83a0705c16b30c80f5b331ae39c605",
		"username": "admin"
	},
	{
		"id": "4162afd27be50892130a3a547340e677",
		"username": "mark"
	},
	{
		"id": "cb967453866a676038a7dd918d65c7c4",
		"username": "mark's another finger"
	}
];
export const enrolledCredentials: Array<{
	id: string;
	userId: string;
	webAuthnUserId: string;
	publicKey: string;
	counter: number;
	transports: string[];
	deviceType: string;
	backedUp: boolean;
}> = [
	{
		"id": "WiZRmAkjrtCcL9sce2tASGhSOXE",
		"userId": "4162afd27be50892130a3a547340e677",
		"webAuthnUserId": "4162afd27be50892130a3a547340e677",
		"publicKey": "pQECAyYgASFYIFAh_ntT3tYkMBbX6cYIzvSygIrGMkFKVWIx_ZHRod2WIlggjj9Sr9t7LLiAW1VT75snN0GKbKkIHo0Tgbt3PIMlDfE",
		"counter": 0,
		"transports": [
			"internal",
			"hybrid"
		],
		"deviceType": "multiDevice",
		"backedUp": true
	},
	{
		"id": "3wGV9BblOIxQApwX_jGpL9ID_uk",
		"userId": "cb967453866a676038a7dd918d65c7c4",
		"webAuthnUserId": "cb967453866a676038a7dd918d65c7c4",
		"publicKey": "pQECAyYgASFYIN8cMQ59tHJUx6F14UgLtMHaJOHNVI63pnQaszpZK-_5Ilggor8u1Cu-VXD2f4JeDlzp9jdADYaGKjkQFcycil35yLg",
		"counter": 0,
		"transports": [
			"internal",
			"hybrid"
		],
		"deviceType": "multiDevice",
		"backedUp": true
	}
];
