/**
 * Export enrolled credentials from SQLite to a TypeScript module
 * for read-only deployment on Vercel.
 *
 * Usage: bun run export
 */

import { Database } from 'bun:sqlite';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

const DB_PATH = resolve('data/app.db');
const OUTPUT_PATH = resolve('src/lib/server/enrolled-data.ts');

const db = new Database(DB_PATH, { readonly: true });

interface UserRow {
	id: string;
	username: string;
}

interface CredentialRow {
	id: string;
	user_id: string;
	webauthn_user_id: string;
	public_key: string;
	counter: number;
	device_type: string;
	backed_up: number;
	transports: string;
}

const users = db.query('SELECT id, username FROM users').all() as UserRow[];
const credentials = db.query('SELECT * FROM credentials').all() as CredentialRow[];

const usersJson = JSON.stringify(
	users.map((u) => ({ id: u.id, username: u.username })),
	null,
	'\t'
);

const credsJson = JSON.stringify(
	credentials.map((c) => ({
		id: c.id,
		userId: c.user_id,
		webAuthnUserId: c.webauthn_user_id,
		publicKey: c.public_key,
		counter: c.counter,
		transports: JSON.parse(c.transports || '[]'),
		deviceType: c.device_type,
		backedUp: c.backed_up === 1
	})),
	null,
	'\t'
);

const output = `// Auto-generated by scripts/export-credentials.ts
// Do not edit manually — run \`bun run export\` to regenerate
export const enrolledUsers: Array<{ id: string; username: string }> = ${usersJson};
export const enrolledCredentials: Array<{
\tid: string;
\tuserId: string;
\twebAuthnUserId: string;
\tpublicKey: string;
\tcounter: number;
\ttransports: string[];
\tdeviceType: string;
\tbackedUp: boolean;
}> = ${credsJson};
`;

writeFileSync(OUTPUT_PATH, output, 'utf-8');

console.log(`Exported ${users.length} users and ${credentials.length} credentials`);
console.log(`Written to: ${OUTPUT_PATH}`);

db.close();
